[versions]
kotlin = "1.9.0"


[libraries]

plugin-kotlin = { group="org.jetbrains.kotlin", name="kotlin-gradle-plugin", version.ref="kotlin" }

[bundles]
plugins-gradle = ["plugin-kotlin"]


[plugins]