[versions]
kotlin = "2.0.20"
lombok = "1.18.34"


[libraries]

lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

plugin-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[bundles]
plugins-gradle = ["plugin-kotlin"]


[plugins]